apps/task_pool/urls.py
"""
Online management app
"""

from django.urls import path

from .views import *

app_name = 'task_pool'

urlpatterns = [


    # 巡检列表
    path('inspection/list', InspectionListView.as_view(), name='Inspection_list'),

    # 完成点检任务单
    path('inspection/done', DoneInspectionListView.as_view(), name='Done_inspection'),

    # 变更巡检责任人
    path('inspection/change_operator', ChangeOperatorView.as_view(), name='change_operator'),

    #巡检任务临时新增
    path('inspection/add', AddInspectionListView.as_view(), name='add_inspection'),



    # 添加任务设定
    path('setting/add', Add_Task_SettingView.as_view(), name='add_task_setting'),

    # 巡检任务设定新增EXCEL
    path('setting/add_excel', Add_By_ExcelView.as_view(), name='add_by_excel'),



    # 维保任务列表
    path('maintenance/list', MaintenanceListView.as_view(), name='Maintenance_list'),

    # 完成维保任务单
    path('maintenance/done', DoneMaintenanceListView.as_view(), name='Done_maintenance'),

    # 变更维保责任人
    path('maintenance/change_operator', ChangeMaintenanceOperatorView.as_view(), name='change_operator_maintenance'),

    #维保任务临时新增
    path('maintenance/add', AddMaintenanceListView.as_view(), name='add_maintenance'),




]

opms/urls.py
"""
opms URL Configuration
"""

from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from opms.settings import MEDIA_ROOT
from django.views.static import serve
from document_management.views import upload_image
from django.conf import settings


# 错误页面
handler403 = 'users.views.permission_denied'
handler404 = 'users.views.page_not_found'
handler500 = 'users.views.page_error'

urlpatterns = [
    path('admin/', admin.site.urls),

    # 静态文件
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}, name='static'),

    # media 配置
    url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),

    # users
    path('', include('users.urls')),

    #
    path('asset/management/', include('asset_management.urls')),


    # platform management
    path('platform/management/', include('platform_management.urls')),

    # message
    path('message/', include('message.urls')),

    # document management
    path('document/', include('document_management.urls')),

    # CKeditor上传图片
    path('uploadimg/', upload_image),

    #task_pool
    path('task_pool/', include('task_pool.urls')),

    # captcha
    path("captcha/", include('captcha.urls')),


]

apps/task_pool/forms.py
######################################
# Django 模块
######################################
from django import forms


######################################
# 自定义模块
######################################
from .models import *

######################################
# 添加巡检任务单
######################################
class AddInspectionListForm(forms.Form):
    area = forms.CharField(required=True)
    machine = forms.CharField( required=True)
    creator = forms.CharField(max_length=20)
    operator1 = forms.CharField(max_length=20, required=True)
    create_time = forms.DateTimeField()
    operator2 = forms.CharField(max_length=20, required=True)
    point = forms.CharField(max_length=20, required=True)
    create_time = forms.DateTimeField()
    cycle = forms.CharField(max_length=20)
    desc = forms.CharField(max_length=200, required=True)
    status = models.CharField()


######################################
# 添加保养任务单
######################################
class AddMaintenanceListForm(forms.Form):
    area = forms.CharField(required=True)
    machine = forms.CharField( required=True)
    creator = forms.CharField(max_length=20)
    operator1 = forms.CharField(max_length=20, required=True)
    create_time = forms.DateTimeField()
    operator2 = forms.CharField(max_length=20, required=True)
    point = forms.CharField(max_length=20, required=True)
    create_time = forms.DateTimeField()
    cycle = forms.CharField(max_length=20)
    desc = forms.CharField(max_length=200, required=True)
    status = models.CharField()

apps/task_pool/views.py
######################################
# Django 模块
######################################
from django.shortcuts import render
from django.views import View
from django.http import HttpResponse
from django.db.models import Q
from django.core.cache import cache

######################################
# 第三方模块
######################################
from pure_pagination import PageNotAnInteger, Paginator

######################################
# 系统模块
######################################

import time
import json
import xlwt#EXCEL 写入文件
import xlrd#EXCEL 读取文件
from io import BytesIO

######################################
# 自建模块--定时生产任务
######################################
from .forms import *
from .models import *


#from .taskscheduler import *


#点检任务列表
######################################
class InspectionListView(View):

    def get(self, request):
        if request.user.role > 1:

            # 页面选择
            web_chose_left_1 = 'task_pool'
            web_chose_left_2 = 'inspection'

            web_title = "点检列表"

            users = UserProfile.objects.filter(status=1)  # 用户信息
            machines = Machine.objects.all()
            areas = Area.objects.all()
            records = InspectionTaskList.objects.all().order_by('-create_time')  # 点检任务清单

            # 搜索，导出条件筛选
            start_time = request.GET.get("start_time", "")
            stop_time = request.GET.get("stop_time", "")
            area_list = request.GET.getlist("area_check", "")
            machine_list = request.GET.getlist("machine_check", "")
            user_list = request.GET.getlist("user_check", "")
            status_list = request.GET.getlist("status_check", "")

            export_data = ""
            # 判断用户操作
            action = request.GET.get("action", "")
            if action == "export_all":
                export_data = records # 导出全部
            if action != "":
                if (action == "search") or (action == "export_search"):
                    if start_time != "":
                        records = records.filter(create_time__gte=start_time)

                    if stop_time != "":
                        records = records.filter(create_time__lte=stop_time)

                    if area_list != "":
                        records = records.filter(area__in=area_list).distinct()

                    if machine_list != "":
                        records = records.filter(machine__in=machine_list).distinct()

                    if user_list != "":

                        records = records.filter(Q(operator1__in=user_list) | Q(operator2__in=user_list)).distinct()

                    if status_list != "":
                        records = records.filter(status__in=status_list).distinct()

                    web_title = '点检任务单查询'

                    if action == "export_search":
                        export_data = records#条件导出

                if (action == "export_search") or (action == "export_all"):
                    # 创建 excel
                    new_excel = xlwt.Workbook(encoding='utf-8')
                    excel_page = new_excel.add_sheet(u'故障记录')

                    # 插入第一行标题
                    excel_page.write(0, 0, u'区域')
                    excel_page.write(0, 1, u'设备名称')
                    excel_page.write(0, 2, u'创建者')
                    excel_page.write(0, 3, u'创建时间')
                    excel_page.write(0, 4, u'负责人1')
                    excel_page.write(0, 5, u'负责人2')
                    excel_page.write(0, 6, u'点检位置')
                    excel_page.write(0, 7, u'作业标准')
                    excel_page.write(0, 8, u'检查结果')
                    excel_page.write(0, 9, u'任务状态')
                    excel_page.write(0, 10, u'作业周期')


                    # 初始行
                    excel_row = 1

                    if (export_data != '') and export_data:
                        for each in export_data:
                            name_excel = each.machine.name
                            area_excel = each.area.name
                            creator_excel = each.creator
                            create_time_excel = each.create_time
                            operator1_excel = each.operator1.chinese_name
                            operator2_excel = each.operator2.chinese_name
                            point_excel = each.point
                            cycle_excel = each.cycle
                            desc_excel = each.desc
                            result_excel = each.result
                            status_excel = ''

                            if each.status == 'done':
                                status_excel = '已处理'

                            if each.status == 'pending':
                                status_excel = '未处理'

                            if each.status == 'other':
                                status_excel = '其它'



                            # 定义时间格式
                            time_style = 'YYYY/MM/DD HH:mm'
                            style = xlwt.XFStyle()
                            style.num_format_str = time_style

                            # 写数据
                            excel_page.write(excel_row, 0, area_excel)
                            excel_page.write(excel_row, 1, name_excel)
                            excel_page.write(excel_row, 2, creator_excel)
                            excel_page.write(excel_row, 3, create_time_excel)
                            excel_page.write(excel_row, 4, operator1_excel)
                            excel_page.write(excel_row, 5, operator2_excel, style)
                            excel_page.write(excel_row, 6, point_excel)
                            excel_page.write(excel_row, 7, desc_excel, style)
                            excel_page.write(excel_row, 8, result_excel)
                            excel_page.write(excel_row, 9, status_excel)
                            excel_page.write(excel_row, 10, cycle_excel)

                            # 行数加1
                            excel_row += 1

                        # 导出文件
                        time_now = time.strftime("%Y%m%d%H%M%S", time.localtime())
                        filename = '点检任务表_' + time_now + '.xls'
                        response = HttpResponse(content_type='application/vnd.ms-excel')
                        response['Content-Disposition'] = 'attachment;filename={}'.format(
                            filename.encode('utf-8').decode("ISO-8859-1"))
                        output = BytesIO()
                        new_excel.save(output)
                        output.seek(0)
                        response.write(output.getvalue())
                        return response

            # 搜索
            keyword = request.GET.get('keyword', '')
            if keyword != '':
                records = records.filter(
                    Q(machine__name__icontains=keyword) | Q(area__name__icontains=keyword) | Q(creator__icontains=keyword) | Q(
                        desc__icontains=keyword) | Q(operator1__chinese_name__icontains=keyword) |
                    Q(operator2__chinese_name__icontains=keyword)| Q(point__icontains=keyword))

            record_nums = records.count()

            # 判断页码
            try:
                page = request.GET.get('page', 1)
            except PageNotAnInteger:
                page = 1

            # 对取到的数据进行分页，记得定义每页的数量
            p = Paginator(records, 15, request=request)

            # 分页处理后的 QuerySet
            records = p.page(page)

            context = {
                'web_chose_left_1': web_chose_left_1,
                'web_chose_left_2': web_chose_left_2,
                'web_title': web_title,
                'users': users,
                'machines': machines,
                'areas': areas,
                'records': records,
                'keyword': keyword,
                'record_nums': record_nums,
                'start_time': start_time,
                'stop_time': stop_time,
                'area_list': area_list,
                'user_list': user_list,
                'machine_list': machine_list,
                'status_list': status_list,
            }

            return render(request, 'task_pool/inspection_list.html', context=context)
        else:
            return HttpResponse(status=403)
#####################################
######################################
# 完成点检记录
######################################

class DoneInspectionListView(View):
    def post(self, request):
        print(request.POST)
        if request.user.role > 1:
            try:
                inspection_obj = InspectionTaskList.objects.get(id=int(request.POST.get("record_id")))
                inspection_obj.status = 'done'
                inspection_obj.save()
                return HttpResponse('{"status":"success", "msg":"删除成功！"}', content_type='application/json')
            except Exception as e:
                return HttpResponse('{"status":"failed", "msg":"未知错误！"}', content_type='application/json')
        else:
            return HttpResponse(status=403)

######################################
# 变更点检任务单责任人
######################################

class ChangeOperatorView(View):
    def post(self, request):

        if request.user.role > 1:
            try:
                inspection_obj = InspectionTaskList.objects.get(id=int(request.POST.get("record_id")))
                inspection_obj.operator1_id=request.POST.get("operator1")
                inspection_obj.operator2_id = request.POST.get("operator2")
                inspection_obj.save()
                return HttpResponse('{"status":"success", "msg":"变更成功！"}', content_type='application/json')
            except Exception as e:
                return HttpResponse('{"status":"failed", "msg":"未知错误！"}', content_type='application/json')
        else:
            return HttpResponse(status=403)

######################################
# 添加巡检任务单
######################################
class AddInspectionListView(View):

templates/task_pool/add_task_setting.html
{% extends 'base.html' %}
{% load static %}
{% load platfom_tags %}
{% load task_pool_tags %}


{% block base_title %}
    {{ web_title }}
{% endblock base_title %}


{% block other_css %}
    <!-- 弹框详情css -->
    <style type="text/css">
        .popover-title {
            color: #1c2b36;
            font-weight: bolder;
        }

        .popover {
            background-color: #1c2b36;
            color: white;
        }
    </style>
{% endblock other_css %}

{% block base_content %}

    <div class="app-content">
        <div class="app-content-body fade-in-up">
            <div class="padder" style="padding-top: 10px;">

                <div class="col-md-12" style="padding-left: 0; padding-right: 0">
                    <div class="panel panel-default" id="body-content">
                        <div class="panel-heading">
                            <div style="display: block; border-left: 5px solid #1c2b36; padding-left: 10px; font-size: 20px; font-weight: bolder; line-height: 25px;color: #1c2b36;">
                                {{ web_title }}
                            </div>
                        </div>

                        <div class="panel-body" id="table_content">

                            <div class="selectBox">
                                <a class="btn btn-sm btn-default" data-toggle="modal"
                                   data-target="#AddInspectionListModal">
                                    <i class="fa fa-plus"></i> EXCEL导入计划
                                </a>


                                <!-- 功能 -->

                                <span style="font-size: 14px; padding-top: 5px;" class="pull-right">共 <b
                                        style="color: orangered">{{ settings_nums }}</b> 条</span>
                            </div>

                            <!-- 列表 -->

                            <div class="row">
                                <div class="col-md-12" style="height:620px; overflow-y:scroll" >
                                    <table class="table table-striped table-hover table-bordered">

                                        <!-- 标题行 -->
                                        <thead   >
                                        <tr role="row" >
                                            <th class="text-center" width="60">ID</th>
                                            <th class="text-center">区域</th>
                                            <th class="text-center">设备名称</th>

                                            <th class="text-center">负责人1</th>
                                            <th class="text-center">负责人2</th>

                                            <th class="text-center">点检位置</th>
                                            <th style="width:400px" class="text-center">作业标准</th>
                                            <th class="text-center">作业周期</th>


                                        </tr>
                                        </thead>

                                         <tbody   >
                                        {% for setting in settings %}
                                            <tr class="gradeX odd" role="row" >
                                                <td class="text-center"
                                                    style="vertical-align:middle;">{{ forloop.counter }}</td>
                                                <td class="text-center"
                                                    style="vertical-align:middle;">{{ setting.0 }}</td>
                                                <td class="text-center"
                                                    style="vertical-align:middle;">{{ setting.1}}</td>
                                                <td class="text-center"
                                                    style="vertical-align:middle;">{{ setting.2}}</td>
                                                <td class="text-center"
                                                    style="vertical-align:middle;">{{ setting.3}}</td>
                                                 <td class="text-center"
                                                    style="vertical-align:middle;">{{ setting.4}}</td>
                                                <td class="text-center"
                                                    style="vertical-align:middle;">{{ setting.5}}</td>
                                                 <td class="text-center"
                                                    style="vertical-align:middle;">{{ setting.6}}</td>

                                            </tr>
                                        {% endfor %}

                                        </tbody>
                                    </table>
                                </div>
                            </div>


                        </div>

                        <div class="panel-footer" style="padding-top: 0; padding-bottom: 0;">
                            <div class="text-center">
                                <ul class="pagination" style="margin-top: 10px; margin-bottom: 10px;">
                                    <a id="SubmitBtn" class="btn btn-default btn-md active" style="margin-right: 50px" role="button">提交</a>
                                    <a href="add" style="margin-left: 50px" class="btn btn-default btn-md active" role="button">放弃</a>

                                </ul>
                            </div>
                        </div>

                    </div>
                </div>


            </div>
        </div>
    </div>

{% endblock base_content %}

{% block base_footer_html %}
    <div class="modal inmodal"  id="AddInspectionListModal" tabindex="-1" role="dialog"
         aria-hidden="true"
         data-backdrop="static">
        <div class="modal-dialog" style="width: 450px;">
            <div class="modal-content" style="margin-top: 100px;">

                <div class="modal-header"
                     style="background-color: #1c2b36; color: white;padding-top: 10px; padding-bottom: 10px;">
                    <button type="button" class="close" data-dismiss="modal">
                        <i class="icon-close" style="font-size: 18px;"></i>
                    </button>
                    <h4 class="modal-title">请选择EXCEL文件</h4>
                </div>
                <div class="form-group">
                    <a style="text-decoration: underline;display: block;text-align:right;margin-right: 10px" href="{% static 'sample_inspection_setting.xls' %}" >查看样本</a>
                    <form style="margin-left: 10px"  method="post" action="add" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input required type="file" name="file">
                        <div style="display: block;text-align: center">
                         <a class="btn btn-md btn-default" style="margin-right: 10px" data-dismiss="modal">取消</a>
                         <input type="submit"style="margin-left: 10px"  class="btn btn-default" value="上传"/>
                        </div>
                     </form>
                </div>
                <div class="modal-footer" style="padding-right: 15px;padding-top: 10px; padding-bottom: 10px;">

                </div>

            </div>
        </div>
    </div>

{% endblock base_footer_html %}


{% block base_footer_js %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap_date/bootstrap-select.css' %}" type="text/css">
    <script src="{% static 'plugins/bootstrap_date/bootstrap-select.js' %}"></script>
    <script src="{% static 'plugins/bootstrap_date/moment-with-locales.min.js' %}"></script>
    <link href="{% static 'plugins/bootstrap_date/bootstrap-datetimepicker.min.css' %}" rel="stylesheet">
    <script src="{% static 'plugins/bootstrap_date/bootstrap-datetimepicker.min.js' %}"></script>


    <!-- 添加记录时间选择器 -->
    <script>
        $('#datetimepicker_add1').datetimepicker({
            format: 'YYYY-MM-DD HH:mm',
            locale:'zh-cn',
        });

        $('#datetimepicker_add2').datetimepicker({
            format: 'YYYY-MM-DD HH:mm',
            locale:'zh-cn',
        });
    </script>
    <script>
            $(function () {
                // 提交表单
                $('#SubmitBtn').on('click', function () {
                    $.ajax({
                        cache: false,
                        type: "POST",
                        url: "{% url 'task_pool:add_by_excel' %}",
                        //data: $('#id_DoneInspectionListForm{{ each_record.id }}').serialize(),
                        async: true,
                        beforeSend: function (xhr, settings) {
                            xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                        },
                        success: function (data) {
                            if (data.status == 'success') {
                                 window.alert(data.msg);
                                window.location.reload();
                            } else if (data.status == 'failed') {
                                window.alert(data.msg);
                            }
                        }
                    });
                });
            })
        </script>


    <!-- 下拉选择框 -->
    <script type="text/javascript">
        $(window).on('load', function () {
            $('.selectpicker').selectpicker({
                'selectedText': 'cat',
                noneSelectedText: '请选择'
            });
        })
    </script>

    <!-- 记录详情 -->
    <script>
        $(function () {
            $("[data-toggle='popover']").popover();
        });
    </script>


{% endblock base_footer_js %}