apps/message/urls.py
"""
message app
"""
from django.urls import path, re_path
from .views import *


app_name = 'message'

urlpatterns = [
    # 消息列表
    path('list/<str:web_tag>', MessageListView.as_view(), name='message_list'),

    # 消息详情
    path('detail/<str:web_tag>/<int:msg_id>', MessageDetailView.as_view(), name='message_detail'),

    # 发送消息
    path('send', SendMessageView.as_view(), name='message_send'),

    # 回复消息
    path('replay', ReplayMessageView.as_view(), name='message_replay'),

    # 上传图片消息
    path('image/upload', UploadMessagImageView.as_view(), name='message_img_upload'),

    # 星标消息
    path('star', StarMessageView.as_view(), name='message_star'),

    # 添加已读
    path('add/read', AddMessageReadView.as_view(), name='message_add_read'),

    # 添加所有已读
    path('add/all/read', AddAllMessageReadView.as_view(), name='message_add_all_read'),
]

opms/urls.py
"""
opms URL Configuration
"""

from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from opms.settings import MEDIA_ROOT
from django.views.static import serve
from document_management.views import upload_image
from django.conf import settings


# 错误页面
handler403 = 'users.views.permission_denied'
handler404 = 'users.views.page_not_found'
handler500 = 'users.views.page_error'

urlpatterns = [
    path('admin/', admin.site.urls),

    # 静态文件
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}, name='static'),

    # media 配置
    url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),

    # users
    path('', include('users.urls')),

    #
    path('asset/management/', include('asset_management.urls')),


    # platform management
    path('platform/management/', include('platform_management.urls')),

    # message
    path('message/', include('message.urls')),

    # document management
    path('document/', include('document_management.urls')),

    # CKeditor上传图片
    path('uploadimg/', upload_image),

    #task_pool
    path('task_pool/', include('task_pool.urls')),

    # captcha
    path("captcha/", include('captcha.urls')),


]

apps/message/models.py
######################################
# Django 模块
######################################
from django.db import models
from django.db.models import Q

######################################
# 系统模块
######################################
import datetime

######################################
# 自定义模块
######################################
from users.models import UserProfile


######################################
# 消息表
######################################
class MessageInfo(models.Model):
    send_user = models.ForeignKey(UserProfile, verbose_name='发送者', related_name='ms_send_user', on_delete=models.CASCADE)
    ms_type = models.PositiveSmallIntegerField(choices=((1, '系统消息'), (2, '私信'), (3, '群发')))
    subject = models.CharField(max_length=100, verbose_name='标题', default='无标题')
    content = models.TextField(verbose_name='内容')
    add_time = models.DateTimeField(verbose_name='添加时间', auto_now_add=True)
    update_time = models.DateTimeField(verbose_name='修改时间', auto_now=True)

    class Meta:
        verbose_name = '消息表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s - %s' % (self.send_user.chinese_name, self.subject)


######################################
# 回复消息表
######################################
class MessageReplayInfo(models.Model):
    message = models.ForeignKey(MessageInfo, verbose_name='消息', related_name='msrep_message', on_delete=models.CASCADE)
    replay_user = models.ForeignKey(UserProfile, verbose_name='回复者', related_name='msrep_send_user', on_delete=models.CASCADE)
    content = models.TextField(verbose_name='内容')
    add_time = models.DateTimeField(verbose_name='添加时间', auto_now_add=True)

    class Meta:
        verbose_name = '回复消息表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s - %s' % (self.message.id, self.replay_user.chinese_name)


######################################
# 用户接受消息表
######################################
class MessageUserInfo(models.Model):
    message = models.ForeignKey(MessageInfo, verbose_name='消息', related_name='msu_message', on_delete=models.CASCADE)
    user = models.ForeignKey(UserProfile, verbose_name='用户', related_name='msu_user', on_delete=models.CASCADE)
    is_star = models.BooleanField(default=False, verbose_name='星标')
    is_read = models.BooleanField(default=False, verbose_name='读取')
    status = models.PositiveSmallIntegerField(choices=((1, '保留'), (2, '删除'), (3, '永久删除')), default=1)

    class Meta:
        verbose_name = '用户接受消息表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s - %s' % (self.message.id, self.user.chinese_name)

apps/message/views.py
######################################
# Django 模块
######################################
from django.shortcuts import render, HttpResponseRedirect, redirect, reverse
from django.views import View
from django.http import HttpResponse
from django.db.models import Q
from django.urls import reverse

######################################
# 第三方模块
######################################
from pure_pagination import PageNotAnInteger, Paginator, EmptyPage

######################################
# 系统模块
######################################
import json
import datetime, time

######################################
# 自建模块
######################################

from .forms import *
from .models import *
from opms.settings import SERVER_URL


######################################
# 消息列表
######################################
class MessageListView(View):
    def get(self, request, web_tag):
        # 页面选择
        web_chose_left_1 = 'user_management'
        web_chose_left_2 = 'user_message'
        web_chose_middle = web_tag

        msgs = MessageUserInfo.objects.filter(user=request.user).filter(status=1)

        title = '收件箱'

        # 发件箱
        if web_tag == 'send_list':
            msgs = msgs.filter(message__send_user=request.user)
            title = '发件箱'

        # 未读信息
        if web_tag == 'unread_list':
            msgs = msgs.filter(is_read=False)
            title = '未读信息'

        # 星标信息
        if web_tag == 'star_list':
            msgs = msgs.filter(is_star=True)
            title = '星标信息'

        # 通知信息
        if web_tag == 'notify_list':
            msgs = msgs.filter(message__ms_type=1)
            title = '通知信息'

        # 搜索
        keyword = request.GET.get('keyword', '')
        if keyword != '':
            msgs = msgs.filter(Q(message__subject__icontains=keyword) | Q(message__content__icontains=keyword) | Q(
                message__send_user__chinese_name__icontains=keyword))

        # 归档
        year = request.GET.get("year", '')
        month = request.GET.get("month", '')

        if (year != '') and (month != ''):
            msgs = msgs.filter(message__add_time__year=int(year), message__add_time__month=int(month))
            web_chose_middle = str(year) + str(month)

        msgs = msgs.order_by('-message__update_time')

        msg_nums = msgs.count()

        # 判断页码
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1

        # 对取到的数据进行分页，记得定义每页的数量
        p = Paginator(msgs, 16, request=request)

        # 分页处理后的 QuerySet
        msgs = p.page(page)

        context = {
            'web_chose_left_1': web_chose_left_1,
            'web_chose_left_2': web_chose_left_2,
            'web_chose_middle': web_chose_middle,
            'msgs': msgs,
            'title': title,
            'keyword': keyword,
            'msg_nums': msg_nums,
        }

        return render(request, 'message/message/message_list.html', context=context)

######################################
# 消息详情
######################################
class MessageDetailView(View):
    def get(self, request, web_tag, msg_id):
        # 页面选择
        web_chose_left_1 = 'user_management'
        web_chose_left_2 = 'user_message'
        web_chose_middle = web_tag

        # 主消息
        msg_start = MessageInfo.objects.get(id=int(msg_id))

        # 回复
        msg_replay = MessageReplayInfo.objects.filter(message_id=int(msg_id))

        # 标记为已读
        user_msg = MessageUserInfo.objects.get(message=msg_start, user=request.user)
        if not user_msg.is_read:
            user_msg.is_read = True
            user_msg.save()

        if not msg_replay:
            msg_replay = ''

        rec_users = MessageUserInfo.objects.filter(message_id=msg_start.id).exclude(user_id=request.user.id)

        context = {
            'web_chose_left_1': web_chose_left_1,
            'web_chose_left_2': web_chose_left_2,
            'web_chose_middle': web_chose_middle,
            'msg_start': msg_start,
            'msg_replay': msg_replay,
            'rec_users': rec_users,
        }

        return render(request, 'message/message/message_detail.html', context=context)


######################################
# 发送消息
######################################
class SendMessageView(View):
    def post(self, request):
        try:
            subject = request.POST.get('subject', '')
            if subject == '':
                subject = '无标题'

            user_id_list = []
            if request.POST.getlist('rec_users'):
                for each_user in request.POST.getlist('rec_users'):
                    user_id_list.append(int(each_user))

            # 获取消息类型
            ms_type = 3

            if len(user_id_list) == 1:
                ms_type = 2

            # 消息内容
            user_msg = request.POST.get('user_msg', '')

            user_msg = user_msg.replace('%%%%%', ';')

            # 保存消息
            message_info = MessageInfo()
            message_info.send_user = request.user
            message_info.ms_type = ms_type
            message_info.subject = subject
            message_info.content = user_msg
            message_info.save()

            # 添加接收用户
            users = UserProfile.objects.filter(status=1, is_active=True)

            if len(user_id_list) == 0:
                for each in users:
                    user_id_list.append(each.id)
            else:
                user_id_list.append(request.user.id)

            for each_user_id in user_id_list:
                message_user_info = MessageUserInfo()
                message_user_info.message_id = message_info.id
                message_user_info.user_id = each_user_id
                message_user_info.is_star = False
                if each_user_id != request.user.id:
                    message_user_info.is_read = False
                else:
                    message_user_info.is_read = True
                message_user_info.status = 1
                message_user_info.save()
            return HttpResponse('{"status":"success", "msg":"发送成功！"}', content_type='application/json')
        except Exception as e:
            return HttpResponse('{"status":"failed", "msg":"发送失败！"}', content_type='application/json')


######################################
# 上传图片
######################################
class UploadMessagImageView(View):
    def post(self, request):
        try:
            # path 修改上传的路径
            path = "media/message/upload/" + time.strftime("%Y%m%d%H%M%S", time.localtime())
            f = request.FILES["file"]
            file_name = path + "_" + f.name
            des_origin_f = open(file_name, "wb+")
            # 直接遍历类文件类型就可以生成迭代器了
            for chunk in f:
                des_origin_f.write(chunk)
            des_origin_f.close()
            img_url = SERVER_URL + '/' + file_name
            context = {
                'status': 'success',
                'img_url': img_url,
            }
            print(img_url)
            return HttpResponse(json.dumps(context), content_type='application/json')
        except Exception as e:
            print(e)
            return HttpResponse('{"status":"failed", "msg":"上传失败！"}', content_type='application/json')


######################################
# 回复消息
######################################
class ReplayMessageView(View):
    def post(self, request):
        try:
            msg_id = request.POST.get('msg_id')

            # 消息内容
            user_msg = request.POST.get('user_msg', '')

            user_msg = user_msg.replace('%%%%%', ';')

            UserReplay = MessageReplayInfo()
            UserReplay.message_id = msg_id
            UserReplay.replay_user_id = request.user.id
            UserReplay.content = user_msg
            UserReplay.save()

            msg_user = MessageUserInfo.objects.filter(message_id=msg_id)
            if msg_user:
                for each in msg_user:
                    if each.user.id != request.user.id:
                        each.is_read = False
                        each.save()

            return HttpResponse('{"status":"success", "msg":"发送成功！"}', content_type='application/json')
        except Exception as e:
            return HttpResponse('{"status":"failed", "msg":"发送失败！"}', content_type='application/json')


######################################
# 星标消息
######################################
class StarMessageView(View):
    def post(self, request):
        try:
            msg_id = int(request.POST.get('msg_id'))
            user_msg = MessageUserInfo.objects.get(message_id=msg_id, user_id=request.user.id)
            if user_msg.is_star:
                user_msg.is_star = False
            else:
                user_msg.is_star = True
            user_msg.save()
            return HttpResponse('{"status":"success", "msg":"星标成功！"}', content_type='application/json')
        except Exception as e:
            return HttpResponse('{"status":"failed", "msg":"星标失败！"}', content_type='application/json')


######################################
# 标记已读
######################################
class AddMessageReadView(View):
    def post(self, request):
        try:
            check_list = request.POST.getlist("msg_check")
            if len(check_list):
                for each in check_list:
                    each_msg = MessageUserInfo.objects.get(message_id=int(each), user=request.user)
                    if not each_msg.is_read:
                        each_msg.is_read = True
                        each_msg.save()
            return HttpResponse('{"status":"success", "msg":"标记已读成功！"}', content_type='application/json')
        except Exception as e:
            return HttpResponse('{"status":"failed", "msg":"标记已读失败！"}', content_type='application/json')


######################################
# 标记所有已读
######################################
class AddAllMessageReadView(View):
    def post(self, request):
        try:

templates/message/message_base.html
{% extends 'base.html' %}
{% load static %}
{% load message_tags %}
{% load user_tags %}

{% block base_header_css %}
    <style>
        .panel {
            margin-bottom: 0px;
        }
    </style>
{% endblock base_header_css %}

{% block base_content %}
    <div class="app-content">
        <div class="app-content-body fade-in-up">
            <div class="padder" style="padding-top: 10px;">

                <!-- 左边导航栏 -->
                <div class="col-sm-2" style="padding-left: 0; padding-right: 10px;">
                    <div class="panel" style="font-size: 14px;">
                        <div>
                            <a class="btn btn-block bg-black" style="background-color: #009688; color: white;"
                               data-toggle="modal"
                               data-target="#WriteMessageModal">写消息</a>
                        </div>

                        <div class="list-group">
                            <a href="{% url 'message:message_list' 'message_list' %}" class="list-group-item"
                               {% ifequal web_chose_middle 'message_list' %}style="background-color: #1c2b36; color: white;"{% endifequal %}>
                                {% ifnotequal request.user.id|Get_UnreadMsg_Nums 0 %}
                                    <span class="badge bg-danger pull-right">{{ request.user.id|Get_UnreadMsg_Nums }}</span>
                                {% endifnotequal %}
                                <i class="fa fa-inbox"></i>&nbsp;&nbsp;&nbsp;&nbsp;收件箱
                            </a>
                        </div>

                        <div class="list-group">
                            <a href="{% url 'message:message_list' 'send_list' %}" class="list-group-item"
                               {% ifequal web_chose_middle 'send_list' %}style="background-color: #1c2b36; color: white;"{% endifequal %}>
                                <i class="fa fa-send-o"></i>&nbsp;&nbsp;&nbsp;&nbsp;发件箱
                            </a>
                        </div>

                        <div class="list-group">
                            <a href="{% url 'message:message_list' 'unread_list' %}" class="list-group-item"
                               {% ifequal web_chose_middle 'unread_list' %}style="background-color: #1c2b36; color: white;"{% endifequal %}>
                                <i class="fa fa-envelope-o"></i>&nbsp;&nbsp;&nbsp;&nbsp;未读消息
                            </a>
                        </div>

                        <div class="list-group">
                            <a href="{% url 'message:message_list' 'notify_list' %}" class="list-group-item"
                               {% ifequal web_chose_middle 'notify_list' %}style="background-color: #1c2b36; color: white;"{% endifequal %}>
                                <i class="fa fa-bell-o"></i>&nbsp;&nbsp;&nbsp;&nbsp;通知消息
                            </a>
                        </div>

                        <div class="list-group">
                            <a href="{% url 'message:message_list' 'star_list' %}" class="list-group-item"
                               {% ifequal web_chose_middle 'star_list' %}style="background-color: #1c2b36; color: white;"{% endifequal %}>
                                <i class="fa fa-star-o"></i>&nbsp;&nbsp;&nbsp;&nbsp;星标消息
                            </a>
                        </div>

                        <div class="list-group">
                            <a class="list-group-item">
                                <i class="fa fa-calendar"></i>&nbsp;&nbsp;&nbsp;&nbsp;消息归档 <span
                                    style="color: orangered;">[ 最新半年 ]</span>
                            </a>

                            {% Get_Latest_Year as ym_list %}
                            {% for each in ym_list %}
                                <div class="list-group" style="margin-bottom: 0;">
                                    {% Get_YM_Str each.0 each.1 as ym_str %}
                                    <a href="{% url 'message:message_list' 'message_list' %}?&year={{ each.0 }}&month={{ each.1 }}" class="list-group-item"
                                        {% if web_chose_middle == ym_str %}style="padding-left: 40px;background-color: #1c2b36; color: white;"{% else %}style="padding-left: 40px; background-color: #DEDEDE;"{% endif %}>
                                        {{ each.0 }} 年 {{ each.1 }} 月
                                        <span class="pull-right">( {% Get_Archives_Nums request.user.id each.0 each.1 %} )</span>
                                    </a>
                                </div>
                            {% endfor %}

                        </div>
                    </div>
                </div>

                <!-- 右边消息列表 -->
                {% block message_content %}
                {% endblock message_content %}

            </div>
        </div>
    </div>

    <!-- 写消息 -->
    <div class="modal inmodal" id="WriteMessageModal" tabindex="-1" role="dialog" aria-hidden="true"
         data-backdrop="static">
        <div class="modal-dialog" style="width: 760px; padding-top: 5%;">
            <div class="modal-content">

                <div class="modal-header" style="background-color: #1c2b36; color: white;padding-top: 10px; padding-bottom: 10px;">
                    <button type="button" class="close" data-dismiss="modal">
                        <i class="icon-close" style="font-size: 18px;"></i>
                    </button>
                    <h4 class="modal-title">发送消息</h4>
                </div>

                <form method="post" id="id_WriteMessageForm">
                    <div class="modal-body">

                        <div class="form-group">
                            <div>
                                <input type="text" name="subject" class="form-control"
                                       placeholder="请输入消息主题（注意，如果不选择收信人将发送给所有人！）"
                                       maxlength="255">
                            </div>
                        </div>

                        <div class="form-group">
                            <div>
                                {% Get_All_Users as users %}
                                <select class="selectpicker form-control" multiple data-live-search="true"
                                        style="display: none;" name="rec_users">
                                    {% for each_user in users %}
                                        {% if each_user.id != request.user.id %}
                                            <option value="{{ each_user.id }}">{{ each_user.chinese_name }}</option>
                                        {% endif %}
                                    {% endfor %}
                                </select>
                            </div>
                        </div>

                        <!-- 消息主体 -->
                        <div class="form-group" style="margin-bottom: 0;">
                            <div class="w-full">
                                <div id="msg_content"><p>在此处输入消息内容!</p></div>
                            </div>
                            <script>
                                $(document).ready(function () {
                                    $('#msg_content').summernote({
                                        height: 250,
                                        lang: 'zh-CN',
                                        placeholder: 'write here...',
                                        focus: true,
                                        toolbar: [
                                            ['undo', ['undo']],
                                            ['style', ['style']],
                                            ['fontname', ['fontname']],
                                            ['style', ['bold', 'italic', 'underline']],
                                            ['fontsize', ['fontsize']],
                                            ['color', ['color']],
                                            ['para', ['ul', 'ol', 'paragraph']],
                                            ['table', ['table']],
                                            ['link', ['link']],
                                            ['picture', ['picture']],
                                            ['codeview', ['codeview']],
                                        ],

                                        callbacks: {
                                            onImageUpload: function (files) {
                                                //上传图片到服务器
                                                var formData = new FormData();
                                                formData.append('file', files[0]);
                                                $.ajax({
                                                    url: '{% url 'message:message_img_upload' %}',//后台文件上传接口
                                                    type: 'POST',
                                                    data: formData,
                                                    processData: false,
                                                    contentType: false,
                                                    beforeSend: function (xhr, settings) {
                                                        xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                                                    },
                                                    success: function (data) {
                                                        console.log(data)
                                                        $('#msg_content').summernote('insertImage', data.img_url);
                                                    }
                                                });
                                            }
                                        }
                                    })
                                });
                            </script>
                        </div>
                    </div>
                </form>

                <div class="modal-footer" style="padding-top: 10px; padding-bottom: 10px;">
                    <a class="btn btn-sm btn-default" data-dismiss="modal">取消</a>
                    <a class="btn btn-sm btn-default" id="id_WriteMessageBtn">发送消息</a>
                </div>

            </div>
        </div>
    </div>

    <script>
        $(function () {
            // 提交表单
            $('#id_WriteMessageBtn').on('click', function () {
                var user_msg = $("#msg_content").summernote('code').replace(/;/g, '%%%%%');
                console.log(user_msg);
                $.ajax({
                    cache: false,
                    type: "POST",
                    url: "{% url 'message:message_send' %}",
                    data: $('#id_WriteMessageForm').serialize() + '&user_msg=' + user_msg,
                    async: true,
                    dataType: 'json',
                    beforeSend: function (xhr, settings) {
                        xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                    },
                    success: function (data) {
                        if (data.status == 'success') {
                            window.location.reload();
                        } else if (data.status == 'failed') {
                            window.alert(data.msg);
                        }
                    }
                });
            });
        })
    </script>

    <script type="text/javascript">
        $(window).on('load', function () {
            $('.selectpicker').selectpicker({
                'selectedText': 'cat'
            });
        });
    </script>
{% endblock base_content %}