apps/users/urls.py
"""
User app
"""
from django.urls import path
#from users.views import *
from .views import *


app_name = 'users'

urlpatterns = [
    # 首页
    path('', IndexView.as_view(), name='index'),

    # 登录
    path('login/', LoginView.as_view(), name='login'),

    # 登出
    path('logout', LogoutView.as_view(), name='logout'),

    # 用户激活请求
    path('email/active', SendActiveUserEmailView.as_view(), name='send_active_email'),

    # 用户激活处理
    path('active/<str:active_code>', ActiveUserView.as_view(), name='active'),

    # 忘记密码
    path('forget', ForgetPasswordView.as_view(), name='forget'),

    # 重置密码
    path('reset/<str:reset_code>', ResetPasswordView.as_view(), name='reset'),

    # 修改密码
    path('modify', ModifyPasswordView.as_view(), name='modify'),

    # 用户信息
    path('user/info', UserInfoView.as_view(), name='user_info'),

    # 他人信息
    path('other/user/info/<int:uid>', OtherUserInfoView.as_view(), name='other_user_info'),

    # 修改用户信息
    path('user/info/change', ChangeUserInfoView.as_view(), name='change_user_info'),

    # 用户头像
    path('user/avatar', UserAvatarView.as_view(), name='user_avatar'),

    # 上传修改用户头像
    path('user/avatar/change/upload', ChangeUserAvatarUploadView.as_view(), name='change_user_avatar_upload'),

    # 选择修改用户头像
    path('user/avatar/change/chose', ChangeUserAvatarChoseView.as_view(), name='change_user_avatar_chose'),

    # 用户密码
    path('user/password', UserPasswordView.as_view(), name='user_password'),

    # 修改用户密码
    path('user/password/change', ChangeUserPasswordView.as_view(), name='change_user_password'),

    # 用户邮箱
    path('user/email', UserEmailView.as_view(), name='user_email'),

    # 用户邮箱验证码
    path('user/email/code', SendChangeUserEmailCodeView.as_view(), name='user_email_code'),

    # 修改用户邮箱
    path('user/email/change', ChangeUserEmailView.as_view(), name='change_user_email'),

    # 用户列表
    path('user/list', UserListView.as_view(), name='user_list'),

    # 添加用户
    path('user/add', AddUserView.as_view(), name='add_user'),

    # 修改用户
    path('user/edit', EditUserView.as_view(), name='edit_user'),

    # 用户登录日志
    path('user/login/record', UserLoginRecordView.as_view(), name='login_record'),

    # 用户操作日志
    path('user/operation/record', UserOperationRecordView.as_view(), name='op_record'),

    # 获取帮助
    path('help', AskHelpView.as_view(), name='help'),
]

opms/urls.py
"""
opms URL Configuration
"""

from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from opms.settings import MEDIA_ROOT
from django.views.static import serve
from document_management.views import upload_image
from django.conf import settings


# 错误页面
handler403 = 'users.views.permission_denied'
handler404 = 'users.views.page_not_found'
handler500 = 'users.views.page_error'

urlpatterns = [
    path('admin/', admin.site.urls),

    # 静态文件
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}, name='static'),

    # media 配置
    url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),

    # users
    path('', include('users.urls')),

    #
    path('asset/management/', include('asset_management.urls')),


    # platform management
    path('platform/management/', include('platform_management.urls')),

    # message
    path('message/', include('message.urls')),

    # document management
    path('document/', include('document_management.urls')),

    # CKeditor上传图片
    path('uploadimg/', upload_image),

    #task_pool
    path('task_pool/', include('task_pool.urls')),

    # captcha
    path("captcha/", include('captcha.urls')),


]

apps/users/models.py
######################################
# Django 模块
######################################
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models import Q


######################################
# 系统模块
######################################
import datetime


######################################
# 公司表
######################################
class UserCompany(models.Model):
    name = models.CharField(verbose_name='公司名称', max_length=30)
    leader = models.CharField(verbose_name='管理', max_length=10)
    desc = models.CharField(verbose_name='描述', max_length=200, blank=True, null=True)
    address = models.CharField(verbose_name='地址', max_length=50, blank=True, null=True)
    add_time = models.DateTimeField(verbose_name='添加时间', auto_now_add=True)

    class Meta:
        verbose_name = '公司'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


######################################
# 部门表
######################################
class UserDepartment(models.Model):
    name = models.CharField(verbose_name='部门名称', max_length=20)
    company = models.ForeignKey(UserCompany, verbose_name='公司', on_delete=models.CASCADE)
    leader = models.CharField(verbose_name='主管', max_length=10)
    desc = models.CharField(verbose_name='描述', max_length=200, blank=True, null=True)
    add_time = models.DateTimeField(verbose_name='添加时间', auto_now_add=True)

    class Meta:
        verbose_name = '部门'
        verbose_name_plural = verbose_name

    def __str__(self):
        return "%s - %s" % (self.company.name, self.name)


######################################
# 职位表
######################################
class UserPosition(models.Model):
    name = models.CharField(verbose_name='名称', max_length=20)
    department = models.ForeignKey(UserDepartment, verbose_name='部门', on_delete=models.CASCADE)
    desc = models.CharField(verbose_name='描述', max_length=200, blank=True, null=True)
    add_time = models.DateTimeField(verbose_name='添加时间', auto_now_add=True)

    class Meta:
        verbose_name = '职位'
        verbose_name_plural = verbose_name

    def __str__(self):
        return "%s - %s - %s" % (self.department.company.name, self.department.name, self.name)


######################################
# 用户扩展表
######################################
class UserProfile(AbstractUser):
    role = models.PositiveSmallIntegerField(verbose_name='角色', choices=((1, '普通用户'), (2, '管理员'), (3, '超级管理员')), default=1)
    chinese_name = models.CharField(verbose_name='中文名', max_length=10)
    english_name = models.CharField(verbose_name='英文名', max_length=20, blank=True, null=True)
    wechat = models.CharField(verbose_name='微信', max_length=30, blank=True, null=True)
    qq = models.CharField(verbose_name='QQ', max_length=20, blank=True, null=True)
    mobile = models.CharField(verbose_name='手机号', max_length=20)
    avatar = models.ImageField(verbose_name='用户头像', max_length=200, upload_to='users/avatar/%Y/%m',
                               default='users/avatar/default.png', null=True, blank=True)
    birthday = models.DateField(verbose_name='生日', blank=True, null=True)
    gender = models.CharField(verbose_name='性别', choices=(('male', '男'), ('female', '女')), default='male',
                              max_length=10)
    address = models.CharField(verbose_name='地址', max_length=50, blank=True, null=True)
    position = models.ForeignKey(UserPosition, verbose_name='职位', on_delete=models.CASCADE, blank=True, null=True)
    desc = models.CharField(verbose_name='描述', max_length=200, blank=True, null=True)
    status = models.PositiveSmallIntegerField(verbose_name='状态', choices=((1, '正常'), (2, '停用')), default=1)
    stop_time = models.DateTimeField(verbose_name='停用时间', blank=True, null=True)

    class Meta:
        verbose_name = '用户'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.username

    # 获取账户添加时间
    def get_join_days(self):
        join_days = ((datetime.datetime.now() - self.date_joined).days + 1)
        return join_days


######################################
# 邮箱验证码表
######################################
class UserEmailVirificationCode(models.Model):
    code = models.CharField(verbose_name='验证码', max_length=20)
    email = models.EmailField(verbose_name='接收邮箱')
    purpose = models.CharField(verbose_name='用途', choices=(
    ('register', '注册'), ('forget', '忘记密码'), ('change_email', '修改邮箱绑定'), ('active', '用户激活')), max_length=20)
    is_use = models.BooleanField(verbose_name='是否被使用', default=False)
    add_time = models.DateTimeField(verbose_name='添加时间', auto_now_add=True)

    class Meta:
        verbose_name = '邮箱验证码'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.email


######################################
# 用户登录信息表
######################################
class UserLoginInfo(models.Model):
    action = models.PositiveSmallIntegerField(verbose_name='动作', choices=((1, '登录'), (2, '注销')), default=1)
    user = models.ForeignKey(UserProfile, verbose_name='用户', on_delete=models.CASCADE)
    agent = models.CharField(verbose_name='客户端', max_length=200)
    ip = models.GenericIPAddressField(verbose_name='IP地址')
    address = models.CharField(verbose_name='登录地区', max_length=100)
    add_time = models.DateTimeField(verbose_name='添加时间', auto_now_add=True)

    class Meta:
        verbose_name = '用户登录信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.user.username


######################################
# 用户反馈
######################################
class UserAskHelp(models.Model):
    user = models.ForeignKey(UserProfile, verbose_name='发送者', related_name='ah_user', on_delete=models.CASCADE)
    subject = models.CharField(verbose_name='标题', max_length=100)
    content = models.TextField(verbose_name='正文')
    add_time = models.DateTimeField(verbose_name='添加时间', auto_now_add=True)

    class Meta:
        verbose_name = '用户反馈'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.user.username

apps/users/forms.py
######################################
# Django 模块
######################################
from django import forms
from captcha.fields import CaptchaField

######################################
# 自定义模块
######################################
from .models import *


######################################
# 用户登录表单
######################################
class UerLoginForm(forms.Form):
    username = forms.CharField(max_length=20, min_length=4, required=True)
    password = forms.CharField(max_length=20, min_length=6, required=True)
    captcha = CaptchaField(error_messages={'invalid': '验证码错误!'})


######################################
# 用户忘记密码表单
######################################
class UserForgetPasswordForm(forms.Form):
    email = forms.EmailField(required=True)


######################################
# 修改用户信息表单
######################################
class ChangeUserInfoForm(forms.Form):
    english_name = forms.CharField(max_length=20, required=False)
    mobile = forms.CharField(max_length=15, required=False)
    wechat = forms.CharField(max_length=20, required=False)
    qq = forms.CharField(max_length=15, required=False)
    address = forms.CharField(max_length=50, required=False)
    desc = forms.Textarea()


######################################
# 修改用户密码表单
######################################
class ChangeUserPasswordForm(forms.Form):
    cur_password = forms.CharField(min_length=6, max_length=20, required=True)
    new_password = forms.CharField(min_length=6, max_length=20, required=True)
    renew_password = forms.CharField(min_length=6, max_length=20, required=True)


######################################
# 添加用户表单
######################################
class AddUserForm(forms.Form):
    username = forms.CharField(min_length=4, max_length=20, required=True)
    chinese_name = forms.CharField(max_length=20, required=True)
    email = forms.EmailField()
    mobile = forms.CharField(min_length=6, max_length=20, required=True)
    password = forms.CharField(min_length=6, max_length=20, required=True)
    re_password = forms.CharField(min_length=6, max_length=20, required=True)


######################################
# 修改用户表单
######################################
class EditUserForm(forms.Form):
    username = forms.CharField(min_length=4, max_length=20, required=True)
    chinese_name = forms.CharField(max_length=20, required=True)
    email = forms.EmailField()
    mobile = forms.CharField(min_length=6, max_length=20, required=True)

templates/users/user/user_change_avatar.html
{% extends 'users/user_base.html' %}
{% load staticfiles %}
{% load user_tags %}


{% block base_title %}
    用户头像
{% endblock base_title %}

{% block base_header_css %}
    <style>
        .chose_pic img {
            border: 2px solid #fff;
        }
    </style>
{% endblock base_header_css %}


{% block user_base_body %}
    <!-- 右边主体 -->
    <div class="col-sm-10" style="padding-left: 0; padding-right: 0;">
        <div class="panel panel-default" id="body-content">
            <div class="panel-heading">
                <div style="display: block; border-left: 5px solid #1c2b36; padding-left: 10px; font-size: 20px; font-weight: bolder; line-height: 25px;color: #1c2b36;">
                    修改头像
                </div>
            </div>

            <div class="row" style="margin-top: 15%;">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    <form method="POST" enctype="multipart/form-data" id="id_UploadAvatarForm">
                        <span style="font-weight: bolder; font-size: 18px;">本地上传一张正方形的头像：</span>

                        <div style="padding-top: 20px;">
                            <input type="file" name="img" id="id_img" onchange="UploadFile2();">
                        </div>
                        <div style="padding-top: 20px;">
                            <input style="width: 100px;" type="button" id="id_UploadAvatarBtn" value="上传">
                        </div>
                    </form>

                    <!-- 点击上传修改用户头像 -->
                    <script>
                        function UploadFile2() {
                            $('#id_img').find('img').remove();
                            var fileobj = $("#id_img")[0].files[0];
                            var form = new FormData();
                            form.append('img', fileobj);
                            $.ajax({
                                type: 'POST',
                                url: '{% url 'users:change_user_avatar_upload' %}',
                                data: form,
                                dataType: 'json',
                                processData: false,
                                contentType: false,
                                beforeSend: function (xhr, settings) {
                                    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                                },
                                success: function (data) {
                                    if (data.status == 'success') {
                                        window.location.reload();
                                    } else if (data.status == 'failed') {
                                        window.alert(data.msg);
                                    }
                                }
                            })
                        }
                    </script>

                    <form method="POST" id="id_ChoseAvatarForm" style="padding-top: 30px;">
                        <span style="font-weight: bolder; font-size: 18px;">选择一张系统头像：</span>

                        <div class="chose_pic" style="padding-top: 20px;">
                            {% for each in for_round %}
                                <div style="display: inline">
                                    <input type="radio" value="users/avatar/{{ each }}.png" name="avatar"
                                           style="display:none">

                                    <img class="img-rounded" src="{{ MEDIA_URL }}users/avatar/{{ each }}.png" width="60"
                                         height="60" onclick="myFun(this.id)" id="id_ChoseAvatarBtn{{ each }}"
                                            {% if each|Compare_Picture:request.user.avatar %}
                                         style="border: 2px solid orangered;"
                                            {% endif %}>
                                </div>

                                {% ifequal each 5 %}
                                    <div></div>
                                {% endifequal %}

                                <!-- 点击修改用户头像 -->
                                <script>
                                    $(function () {
                                        // 提交表单
                                        $('#id_ChoseAvatarBtn{{ each }}').on('click', function () {
                                            $.ajax({
                                                cache: false,
                                                type: "POST",
                                                url: "{% url 'users:change_user_avatar_chose' %}",
                                                data: $('#id_ChoseAvatarForm').serialize(),
                                                async: true,
                                                beforeSend: function (xhr, settings) {
                                                    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                                                },
                                                success: function (data) {
                                                    if (data.status == 'success') {
                                                        window.location.reload();
                                                    } else if (data.status == 'failed') {
                                                        window.alert(data.msg);
                                                    }
                                                }
                                            });
                                        });
                                    })
                                </script>

                            {% endfor %}

                        </div>
                    </form>

                </div>
                <div class="col-md-4"></div>
            </div>
        </div>
    </div>
{% endblock user_base_body %}


{% block base_footer_js %}
    <!-- 点击修改用户头像 -->
    <script>
        function myFun(sId) {
            var oImg = document.getElementsByTagName('img');
            for (var i = 0; i < oImg.length; i++) {
                if (oImg[i].id == sId) {
                    oImg[i].previousSibling.previousSibling.checked = true;
                    oImg[i].style.border = '2px solid orangered';
                } else {
                    oImg[i].style.border = '2px solid white';
                }
            }
        }
    </script>
{% endblock base_footer_js %}

templates/users/user/user_change_email.html
{% extends 'users/user_base.html' %}
{% load staticfiles %}


{% block base_title %}
    修改邮箱
{% endblock base_title %}


{% block user_base_body %}
    <!-- 右边主体 -->
    <div class="col-sm-10" style="padding-left: 0; padding-right: 0;">
        <div class="panel panel-default" id="body-content">

            <div class="panel-heading">
                <div style="display: block; border-left: 5px solid #1c2b36; padding-left: 10px; font-size: 20px; font-weight: bolder; line-height: 25px;color: #1c2b36;">
                    修改邮箱
                </div>
            </div>


            <div class="row" style="margin-top: 15%;">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    <div style="padding-left: 10%;padding-right: 10%;">
                        <p class="m-t"></p>

                        <p style="margin-bottom: 0; font-size: 15px;">
                            请输入你想修改后的邮箱地址！
                        </p>

                        <div class="row">
                            <div class="col-lg-12">
                                <form class="m-t" role="form" action="" method="post" id="id_SendChangeEmailCodeForm">
                                    <div class="form-group">
                                        <input name="email" class="form-control" placeholder="邮箱地址"
                                               required="">
                                    </div>

                                    <div class="row">
                                        <div class="form-group col-md-8">
                                            <input name="code" class="form-control" placeholder="验证码"
                                                   required="">
                                        </div>

                                        <div class="form-group col-md-4">
                                            <a class="btn full-width btn-black block" style="color: white;" id="id_SendChangeEmailCodeBtn">获取验证码</a>
                                        </div>
                                    </div>

                                    <a class="btn btn-black block full-width m-b" style="color: white;" id="id_ChangeEmailBtn">确认修改</a>
                                </form>
                            </div>
                        </div>
                        <p class="m-t"></p>
                    </div>
                </div>
                <div class="col-md-4"></div>
            </div>
        </div>
    </div>
{% endblock user_base_body %}


{% block base_footer_js %}
    <!-- 发送验证码 -->
    <script>
        $(function () {
            // 提交表单
            $('#id_SendChangeEmailCodeBtn').on('click', function () {
                $.ajax({
                    cache: false,
                    type: "POST",
                    url: "{% url 'users:user_email_code' %}",
                    data: $('#id_SendChangeEmailCodeForm').serialize(),
                    async: true,
                    beforeSend: function (xhr, settings) {
                        xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                    },
                    success: function (data) {
                        if (data.status == 'success') {
                            window.alert(data.msg);
                            document.getElementById('id_SendChangeEmailCodeBtn').innerHTML="已发送";
                        } else if (data.status == 'failed') {
                            window.alert(data.msg);
                        }
                    }
                });
            });
        })
    </script>

    <!-- 修改用户邮箱 -->
    <script>
        $(function () {
            // 提交表单
            $('#id_ChangeEmailBtn').on('click', function () {
                $.ajax({
                    cache: false,
                    type: "POST",
                    url: "{% url 'users:change_user_email' %}",
                    data: $('#id_SendChangeEmailCodeForm').serialize(),
                    async: true,
                    beforeSend: function (xhr, settings) {
                        xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                    },
                    success: function (data) {
                        if (data.status == 'success') {
                            window.alert(data.msg);
                            window.location.href='{% url 'users:user_info' %}';
                        } else if (data.status == 'failed') {
                            window.alert(data.msg);
                        }
                    }
                });
            });
        })
    </script>
{% endblock base_footer_js %}

templates/users/user/user_change_passwd.html
{% extends 'users/user_base.html' %}
{% load static %}


{% block base_title %}
    用户信息
{% endblock base_title %}


{% block user_base_body %}
    <!-- 右边主体 -->
    <div class="col-sm-10" style="padding-left: 0; padding-right: 0;">
        <div class="panel panel-default" id="body-content">

            <div class="panel-heading">
                <div style="display: block; border-left: 5px solid #1c2b36; padding-left: 10px; font-size: 20px; font-weight: bolder; line-height: 25px;color: #1c2b36;">
                    修改密码
                </div>
            </div>

            <div class="row" style="margin-top: 15%;">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    <div style="padding-left: 10%;padding-right: 10%;">
                        <p class="m-t"></p>

                        <p style="margin-bottom: 0; font-size: 15px;">
                            请输入一个既能被你记住，同时又有复杂度的密码！
                        </p>

                        <div class="row">
                            <div class="col-lg-12">
                                <form class="m-t" role="form" action="{% url 'users:change_user_password' %}" method="post">
                                    {% csrf_token %}
                                    <p style="color: red;">{{ msg }}</p>
                                    <div class="form-group">
                                        <input name="cur_password" class="form-control" type="password" placeholder="当前密码"
                                               required="">
                                    </div>
                                    <div class="form-group">
                                        <input name="new_password" class="form-control" type="password" placeholder="新密码"
                                               required="" onKeyUp=pwStrength(this.value)
                                               onBlur=pwStrength(this.value)>
                                    </div>

                                    <div class="form-group">
                                        <table border="1"
                                               style="border: lightgrey; height: 5px; width: 100%">
                                            <tr>
                                                <td id="strength_L"></td>
                                                <td id="strength_M"></td>
                                                <td id="strength_H"></td>
                                            </tr>
                                        </table>
                                    </div>

                                    <div class="form-group">
                                        <input name="renew_password" type="password" class="form-control" placeholder="重复密码"
                                               required="">
                                    </div>
                                    <button type="submit" class="btn btn-black block full-width m-b"
                                            style="color: white">修改密码
                                    </button>
                                </form>
                            </div>
                        </div>
                        <p class="m-t"></p>
                    </div>
                </div>
                <div class="col-md-4"></div>
            </div>
        </div>
    </div>
{% endblock user_base_body %}


{% block base_footer_js %}
    <script language=javascript>
        // 判断输入密码的类型
        function CharMode(iN) {
            //数字
            if (iN >= 48 && iN <= 57)
                return 1;
            //大写
            if (iN >= 65 && iN <= 90)
                return 2;
            //小写
            if (iN >= 97 && iN <= 122)
                return 4;
            else
                return 8;
        }

        // 计算密码模式
        function bitTotal(num) {
            modes = 0;
            for (i = 0; i < 4; i++) {
                if (num & 1) modes++;
                num >>>= 1;
            }
            return modes;
        }

        // 返回强度级别
        function checkStrong(sPW) {
            // 密码太短，不检测级别
            if (sPW.length < 6)
                return 0;
            Modes = 0;
            for (i = 0; i < sPW.length; i++) {
                // 密码模式
                Modes |= CharMode(sPW.charCodeAt(i));
            }
            return bitTotal(Modes);
        }

        // 显示颜色
        function pwStrength(pwd) {
            // 默认颜色
            Dfault_color = "white";
            // 低强度的颜色，且只显示在最左边的单元格中
            L_color = "red";
            // 中等强度的颜色，且只显示在左边两个单元格中
            M_color = "yellow";
            // 高强度的颜色，三个单元格都显示
            H_color = "green";
            if (pwd == null || pwd == '') {
                Lcolor = Mcolor = Hcolor = Dfault_color;
            }
            else {
                S_level = checkStrong(pwd);
                switch (S_level) {
                    case 0:
                        Lcolor = Mcolor = Hcolor = Dfault_color;
                        break;
                    case 1:
                        Lcolor = L_color;
                        Mcolor = Hcolor = Dfault_color;
                        break;
                    case 2:
                        Lcolor = Mcolor = M_color;
                        Hcolor = Dfault_color;
                        break;
                    default:
                        Lcolor = Mcolor = Hcolor = H_color;
                }
            }
            document.getElementById("strength_L").style.background = Lcolor;
            document.getElementById("strength_M").style.background = Mcolor;
            document.getElementById("strength_H").style.background = Hcolor;
        }
    </script>
{% endblock base_footer_js %}