apps/users/urls.py
"""
User app
"""
from django.urls import path
#from users.views import *
from .views import *


app_name = 'users'

urlpatterns = [
    # 首页
    path('', IndexView.as_view(), name='index'),

    # 登录
    path('login/', LoginView.as_view(), name='login'),

    # 登出
    path('logout', LogoutView.as_view(), name='logout'),

    # 用户激活请求
    path('email/active', SendActiveUserEmailView.as_view(), name='send_active_email'),

    # 用户激活处理
    path('active/<str:active_code>', ActiveUserView.as_view(), name='active'),

    # 忘记密码
    path('forget', ForgetPasswordView.as_view(), name='forget'),

    # 重置密码
    path('reset/<str:reset_code>', ResetPasswordView.as_view(), name='reset'),

    # 修改密码
    path('modify', ModifyPasswordView.as_view(), name='modify'),

    # 用户信息
    path('user/info', UserInfoView.as_view(), name='user_info'),

    # 他人信息
    path('other/user/info/<int:uid>', OtherUserInfoView.as_view(), name='other_user_info'),

    # 修改用户信息
    path('user/info/change', ChangeUserInfoView.as_view(), name='change_user_info'),

    # 用户头像
    path('user/avatar', UserAvatarView.as_view(), name='user_avatar'),

    # 上传修改用户头像
    path('user/avatar/change/upload', ChangeUserAvatarUploadView.as_view(), name='change_user_avatar_upload'),

    # 选择修改用户头像
    path('user/avatar/change/chose', ChangeUserAvatarChoseView.as_view(), name='change_user_avatar_chose'),

    # 用户密码
    path('user/password', UserPasswordView.as_view(), name='user_password'),

    # 修改用户密码
    path('user/password/change', ChangeUserPasswordView.as_view(), name='change_user_password'),

    # 用户邮箱
    path('user/email', UserEmailView.as_view(), name='user_email'),

    # 用户邮箱验证码
    path('user/email/code', SendChangeUserEmailCodeView.as_view(), name='user_email_code'),

    # 修改用户邮箱
    path('user/email/change', ChangeUserEmailView.as_view(), name='change_user_email'),

    # 用户列表
    path('user/list', UserListView.as_view(), name='user_list'),

    # 添加用户
    path('user/add', AddUserView.as_view(), name='add_user'),

    # 修改用户
    path('user/edit', EditUserView.as_view(), name='edit_user'),

    # 用户登录日志
    path('user/login/record', UserLoginRecordView.as_view(), name='login_record'),

    # 用户操作日志
    path('user/operation/record', UserOperationRecordView.as_view(), name='op_record'),

    # 获取帮助
    path('help', AskHelpView.as_view(), name='help'),
]

opms/urls.py
"""
opms URL Configuration
"""

from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from opms.settings import MEDIA_ROOT
from django.views.static import serve
from document_management.views import upload_image
from django.conf import settings


# 错误页面
handler403 = 'users.views.permission_denied'
handler404 = 'users.views.page_not_found'
handler500 = 'users.views.page_error'

urlpatterns = [
    path('admin/', admin.site.urls),

    # 静态文件
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}, name='static'),

    # media 配置
    url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),

    # users
    path('', include('users.urls')),

    #
    path('asset/management/', include('asset_management.urls')),


    # platform management
    path('platform/management/', include('platform_management.urls')),

    # message
    path('message/', include('message.urls')),

    # document management
    path('document/', include('document_management.urls')),

    # CKeditor上传图片
    path('uploadimg/', upload_image),

    #task_pool
    path('task_pool/', include('task_pool.urls')),

    # captcha
    path("captcha/", include('captcha.urls')),


]

apps/users/forms.py
######################################
# Django 模块
######################################
from django import forms
from captcha.fields import CaptchaField

######################################
# 自定义模块
######################################
from .models import *


######################################
# 用户登录表单
######################################
class UerLoginForm(forms.Form):
    username = forms.CharField(max_length=20, min_length=4, required=True)
    password = forms.CharField(max_length=20, min_length=6, required=True)
    captcha = CaptchaField(error_messages={'invalid': '验证码错误!'})


######################################
# 用户忘记密码表单
######################################
class UserForgetPasswordForm(forms.Form):
    email = forms.EmailField(required=True)


######################################
# 修改用户信息表单
######################################
class ChangeUserInfoForm(forms.Form):
    english_name = forms.CharField(max_length=20, required=False)
    mobile = forms.CharField(max_length=15, required=False)
    wechat = forms.CharField(max_length=20, required=False)
    qq = forms.CharField(max_length=15, required=False)
    address = forms.CharField(max_length=50, required=False)
    desc = forms.Textarea()


######################################
# 修改用户密码表单
######################################
class ChangeUserPasswordForm(forms.Form):
    cur_password = forms.CharField(min_length=6, max_length=20, required=True)
    new_password = forms.CharField(min_length=6, max_length=20, required=True)
    renew_password = forms.CharField(min_length=6, max_length=20, required=True)


######################################
# 添加用户表单
######################################
class AddUserForm(forms.Form):
    username = forms.CharField(min_length=4, max_length=20, required=True)
    chinese_name = forms.CharField(max_length=20, required=True)
    email = forms.EmailField()
    mobile = forms.CharField(min_length=6, max_length=20, required=True)
    password = forms.CharField(min_length=6, max_length=20, required=True)
    re_password = forms.CharField(min_length=6, max_length=20, required=True)


######################################
# 修改用户表单
######################################
class EditUserForm(forms.Form):
    username = forms.CharField(min_length=4, max_length=20, required=True)
    chinese_name = forms.CharField(max_length=20, required=True)
    email = forms.EmailField()
    mobile = forms.CharField(min_length=6, max_length=20, required=True)

apps/users/views.py
######################################
# Django 模块
######################################
from django.shortcuts import render, HttpResponseRedirect
from django.views import View
from django.contrib.auth import login, logout, authenticate
from django.http import HttpResponse
from django.contrib.auth.backends import ModelBackend
from django.contrib.auth.hashers import make_password
from django.urls import reverse
from django.core.mail import send_mail


######################################
# 第三方模块
######################################
from pure_pagination import PageNotAnInteger, Paginator

######################################
# 系统模块
######################################

######################################
# 自建模块
######################################
from .forms import *
from .models import *
from operation_record.models import UserOperationRecord
from utils.send_email import send_email_verificode
from opms.settings import GAODE_API_KEY, CITY_ID, DEVELPER_EMAIL_ADDRESS, EMAIL_HOST_USER
#from online_management.models import TroubleRecord, DeployRecord


######################################
# 首页
######################################
class IndexView(View):
    def get(self, request):
        web_chose_left_1 = 'index'
        web_chose_left_2 = ''
        web_chose_middle = ''

        # 客户端 IP
        # x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        # if x_forwarded_for:
        #     agent_ip = x_forwarded_for.split(',')[-1].strip()
        # else:
        #     agent_ip = request.META.get('REMOTE_ADDR')
        #
        # # 获取城市
        # url = "http://ip.taobao.com/service/getIpInfo.php?ip="
        # data = urllib.request.urlopen(url + agent_ip).read().decode("utf-8")
        # datadict = json.loads(data)
        # for oneinfo in datadict:
        #     if "code" == oneinfo:
        #         if datadict[oneinfo] == 0:
        #             county = datadict["data"]["city"]
        #             if county != '内网IP':
        #                 city_id = datadict["data"]["city_id"]
        #             else:
        #                 city_id = CITY_ID

        # 获取天气
        # url = "https://restapi.amap.com/v3/weather/weatherInfo?city=%s&key=%s" % (city_id, GAODE_API_KEY)
        # data = urllib.request.urlopen(url).read().decode("utf-8")
        # datadict = json.loads(data)
        # weather_name = datadict["lives"][0]["weather"]
        # temperature = datadict["lives"][0]["temperature"]

        # API 天气列表
        # rain_list = ['阵雨', '小雨', '中雨', '大雨', '暴雨', '大暴雨', '特大暴雨', '冻雨', '小雨-中雨', '中雨-大雨', '大雨-暴雨', '暴雨-大暴雨', '大暴雨-特大暴雨']
        # thunder_list = ['雷阵雨', '雷阵雨并伴有冰雹']
        # snow_list = ['雨夹雪', '阵雪', '小雪', '中雪', '大雪', '暴雪', '小雪-中雪', '中雪-大雪', '大雪-暴雪', '弱高吹雪']
        # sun_list = ['晴', ]
        # cloud_list = ['阴', '多云', '雾', '沙尘暴', '浮尘', '扬沙', '强沙尘暴', '飑', '龙卷风', '轻雾', '霾']

        # 判断天气
        # if weather_name in rain_list:
        #     weather = 'rain'
        # elif weather_name in thunder_list:
        #     weather = 'thunder'
        # elif weather_name in snow_list:
        #     weather = 'snow'
        # elif weather_name in sun_list:
        #     weather = 'sun'
        # elif weather_name in cloud_list:
        #     weather = 'cloud'
        # else:
        #     weather = 'unknow'

        weather_name = '晴'
        weather = 'sun'
        temperature = '0'

        # 获取年月列表
        ym_list = []
        tr_list = []
        dep_list = []
        y_now = datetime.datetime.now().year
        m_now = datetime.datetime.now().month
        i = 0
        while (i < 12):
            ym_list.append(str(y_now) + '-' + str(m_now))
           # tr_list.append(TroubleRecord.objects.filter(event_time__year=y_now, event_time__month=m_now).count())
            #dep_list.append(DeployRecord.objects.filter(deploy_time__year=y_now, deploy_time__month=m_now).count())

            m_now = m_now - 1
            if m_now == 0:
                m_now = 12
                y_now = y_now - 1

            i += 1

        tr_list = list(reversed(tr_list))
        ym_list = list(reversed(ym_list))
        dep_list = list(reversed(dep_list))

        context = {
            'web_chose_left_1': web_chose_left_1,
            'web_chose_left_2': web_chose_left_2,
            'web_chose_middle': web_chose_middle,
            'weather_name': weather_name,
            'weather': weather,
            'temperature': temperature,
            'ym_list': ym_list,
            'tr_list': tr_list,
            'dep_list': dep_list,
            'Get_Latest_Trouble':{'name':'A','get_handle_result_display':'GOOD','event_time':datetime.datetime.now()}
        }

        return render(request, 'users/index.html', context=context)


######################################
# 登录
######################################
class LoginView(View):
    def get(self, request):
        user_login_form = UerLoginForm()
        context = {
            'user_login_form': user_login_form,
        }
        return render(request, 'users/login/login.html', context=context)

    def post(self, request):
        user_login_form = UerLoginForm(request.POST)

        # 输入合法
        if user_login_form.is_valid():
            # 获取提交的登录信息
            login_username = request.POST.get('username')
            login_password = request.POST.get('password')


            # 认证用户
            user = authenticate(username=login_username, password=login_password)

            # 判断用户是否正确
            if user is not None:
                if not user.is_active:
                    return HttpResponseRedirect(reverse('users:send_active_email'))
                elif (user.status != 1):
                    msg = '用户已停用，请联系管理员！'
                else:
                    uid1 = UserProfile.objects.get(username=login_username).id

                    # 判断用户是否登录
                    # all_session = Session.objects.all()
                    #
                    # if all_session is not None:
                    #     for session in all_session:
                    #         uid2 = session.get_decoded().get('_auth_user_id')
                    #         if uid1 == uid2:
                    #             session.delete()

                    login(request, user)

                    # 保存登录信息
                    login_record = UserLoginInfo()
                    login_record.action = 1
                    login_record.user = user
                    login_record.agent = request.META['HTTP_USER_AGENT']
                    login_record.ip = request.META['REMOTE_ADDR']
                    login_record.address = '中国 广东 深圳'
                    # login_record.address = get_ip_location(request.META['REMOTE_ADDR'])
                    login_record.save()

                    # 添加操作记录
                    op_record = UserOperationRecord()
                    op_record.op_user = user
                    op_record.belong = 3
                    op_record.status = 1
                    op_record.op_num = user.id
                    op_record.operation = 5
                    op_record.action = "用户 [ %s ] 登录了系统" % user.chinese_name
                    op_record.save()

                    return HttpResponseRedirect(reverse('users:index'))
            else:
                msg = '用户名或密码错误！'

            # 账户有问题的情况
            context = {
                'msg': msg,
                'user_login_form': user_login_form,
            }
            return render(request, 'users/login/login.html', context=context)
        else:
            # msg = '用户账户或密码不满足长度要求！'
            context = {
                # 'msg': msg,
                'user_login_form': user_login_form,
            }
            return render(request, 'users/login/login.html', context=context)


######################################
# 邮箱登录
######################################
class OtherLoginBackend(ModelBackend):
    def authenticate(self, request, username=None, password=None, **kwargs):
        try:
            # 增加邮箱验证
            user = UserProfile.objects.get(Q(username=username) | Q(email=username))
            if user.check_password(password):
                return user
        except Exception as e:
            return None


######################################
# 登出
######################################
class LogoutView(View):
    def get(self, request):
        # 保存登录信息
        login_record = UserLoginInfo()
        login_record.action = 2
        login_record.user = request.user
        login_record.agent = request.META['HTTP_USER_AGENT']
        login_record.ip = request.META['REMOTE_ADDR']
        # login_record.address = get_ip_location(request.META['REMOTE_ADDR'])
        login_record.address = '中国 广东 深圳'
        login_record.save()

        # 添加操作记录
        op_record = UserOperationRecord()
        op_record.op_user = request.user
        op_record.belong = 3
        op_record.status = 1
        op_record.op_num = request.user.id
        op_record.operation = 6
        op_record.action = "用户 [ %s ] 退出了系统" % request.user.chinese_name
        op_record.save()

        logout(request)

        return HttpResponseRedirect(reverse('users:login'))


######################################
# 用户激活请求
######################################
class SendActiveUserEmailView(View):
    def get(self, request):
        context = {}
        return render(request, 'users/login/active_user.html', context=context)

    def post(self, request):
        email = request.POST.get('email')

        if UserProfile.objects.filter(email=email):
            user = UserProfile.objects.get(email=email)
            if user.is_active:
                msg = '该用户已经激活！'
            else:
                # 发送邮件
                send_status = send_email_verificode(email, 'active')
                if send_status:
                    msg = '邮件已发送，请注意查收！'
                    context = {
                        'msg': msg,
                    }

templates/users/help.html
{% extends 'base.html' %}
{% load static %}

{% block base_title %}
    获取帮助
{% endblock base_title %}


{% block base_content %}

    <!-- 右边主体 -->
    <div class="app-content">
        <div class="app-content-body fade-in-up">
            <div class="padder" style="padding-top: 10px;">

                <div class="col-md-12" style="padding-left: 0; padding-right: 0;">
                    <div class="panel panel-default" id="body-content">
                        <div class="panel-heading">
                            <div style="display: block; border-left: 5px solid #1c2b36; padding-left: 10px; font-size: 20px; font-weight: bolder; line-height: 25px;color: #1c2b36;">
                                帮助反馈
                            </div>
                        </div>

                        <div class="panel-body" id="table_content">

                            <div class="row" style="margin-top: 5%;">
                                <div class="col-md-3"></div>
                                <div class="col-md-6">
                                    <div>
                                        <p class="m-t"></p>

                                        <div class="row">
                                            <div class="col-lg-12">
                                                <form method="post" action="{% url 'users:help' %}">

                                                    {% csrf_token %}

                                                    <span style="color: red; margin-bottom: 10px;">{{ msg }}</span>

                                                    <div class="form-group">
                                                        <div>
                                                            <input type="text" name="subject" class="form-control"
                                                                   placeholder="请输入反馈的主题"
                                                                   maxlength="255">
                                                        </div>
                                                    </div>

                                                    <!-- 消息主体 -->
                                                    <div class="form-group" style="margin-bottom: 0;">
                                                            <textarea class="form-control" placeholder="请输入反馈的内容"
                                                                      name="content" rows="20"></textarea>
                                                    </div>

                                                    <div style="margin-top: 15px;">
                                                        <button type="submit" class="btn btn-black block full-width m-b"
                                                                style="color: white;">提交反馈
                                                        </button>
                                                    </div>
                                                </form>

                                            </div>
                                        </div>
                                        <p class="m-t"></p>
                                    </div>
                                </div>
                                <div class="col-md-3"></div>
                            </div>

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock base_content %}

templates/users/login_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


<!-- =============================================================================== -->
<!-- 头部开始 -->
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <!-- 标题 -->
    <title>
        {% block login_base_title %}
        {% endblock login_base_title %}
        | OPMS 运维管理系统
    </title>

    <!-- css -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/app.css' %}" rel="stylesheet">

    <!-- js -->
    <script src="{% static 'js/jquery-2.2.4.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<!-- 头部结束 -->
<!-- =============================================================================== -->



<!-- =============================================================================== -->
<!-- 主体开始 -->
<body style="background-color: #1c2b36">

<!-- 页面主体 -->
{% block login_base_body %}
{% endblock login_base_body %}


<!-- 其它js -->
{% block login_base_footerjs %}
{% endblock login_base_footerjs %}


</body>
<!-- 主体结束 -->
<!-- =============================================================================== -->


</html>

templates/users/user_base.html
{% extends 'base.html' %}
{% load static %}


{% block base_content %}
    <div class="app-content">
        <div class="app-content-body fade-in-up">
            <div class="padder" style="padding-top: 10px;">

                <!-- 左边导航栏 -->
                <div class="col-sm-2" style="padding-left: 0; padding-right: 10px;">
                    <div class="panel" style="font-size: 14px;">
                        <div class="list-group">
                            <a href="{% url 'users:user_info' %}" class="list-group-item"
                               {% ifequal web_chose_middle 'user_info' %}style="background-color: #1c2b36; color: white;"{% endifequal %}>
                                <i class="fa fa-credit-card"></i>&nbsp;&nbsp;&nbsp;&nbsp;个人资料
                            </a>
                        </div>

                        <div class="list-group">
                            <a href="{% url 'users:user_password' %}" class="list-group-item"
                               {% ifequal web_chose_middle 'user_password' %}style="background-color: #1c2b36; color: white;"{% endifequal %}>
                                <i class="fa fa-key"></i>&nbsp;&nbsp;&nbsp;&nbsp;修改密码
                            </a>
                        </div>

                        <div class="list-group">
                            <a href="{% url 'users:user_email' %}" class="list-group-item"
                               {% ifequal web_chose_middle 'user_email' %}style="background-color: #1c2b36; color: white;"{% endifequal %}>
                                <i class="fa fa-envelope-o"></i>&nbsp;&nbsp;&nbsp;&nbsp;修改邮箱
                            </a>
                        </div>

                        <div class="list-group">
                            <a href="{% url 'users:user_avatar' %}" class="list-group-item"
                               {% ifequal web_chose_middle 'user_avatar' %}style="background-color: #1c2b36; color: white;"{% endifequal %}>
                                <i class="fa fa-meh-o"></i>&nbsp;&nbsp;&nbsp;&nbsp;修改头像
                            </a>
                        </div>
                    </div>
                </div>

                <!-- 右边主体 -->
                {% block user_base_body %}
                {% endblock user_base_body %}
            </div>
        </div>
    </div>
{% endblock base_content %}